import { useState, useRef, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import html2pdf from "html2pdf.js";
import api from "../services/api";

const INITIAL_MESSAGE = {
  role: "assistant",
  content: "Hello! I'm ClearFlow AI. Ask me anything about your finances — transactions, invoices, cash flow, or anything else.",
};

const SUGGESTED_QUESTIONS = [
  { label: "P&L this month", question: "Show me a Profit & Loss statement for this month" },
  { label: "Top expenses", question: "What are my top 5 expense categories this month?" },
  { label: "Cash flow summary", question: "Give me a cash flow summary for the last 3 months" },
  { label: "Unpaid invoices", question: "How many invoices are pending or unpaid?" },
  { label: "Biggest transactions", question: "What are my 5 largest transactions this month?" },
  { label: "Monthly comparison", question: "Compare my income and expenses between last month and this month" },
];

function AssistantMessage({ content }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const date = new Date().toLocaleString();

    // Convert markdown to HTML
    const bodyHtml = content
      .replace(/^### (.+)$/gm, "<h3>$1</h3>")
      .replace(/^## (.+)$/gm, "<h2>$1</h2>")
      .replace(/^# (.+)$/gm, "<h1>$1</h1>")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.+?)\*/g, "<em>$1</em>")
      .replace(/^---$/gm, "<hr>")
      .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
      .replace(/^- (.+)$/gm, "<li>$1</li>")
      .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
      .replace(/(\|.+\|\n)(\|[-:| ]+\|\n)((?:\|.+\|\n?)+)/g, (match) => {
        const lines = match.trim().split("\n").filter(Boolean);
        const headers = lines[0].split("|").filter(Boolean).map(h => `<th>${h.trim()}</th>`).join("");
        const rows = lines.slice(2).map(row =>
          `<tr>${row.split("|").filter(Boolean).map(c => `<td>${c.trim()}</td>`).join("")}</tr>`
        ).join("");
        return `<table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>`;
      })
      .replace(/\n\n/g, "</p><p>")
      .replace(/\n/g, "<br>");

    const container = document.createElement("div");
    container.innerHTML = `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#1f2937;line-height:1.6;padding:8px">
        <div style="border-bottom:2px solid #2563eb;padding-bottom:10px;margin-bottom:20px">
          <div style="color:#2563eb;font-size:20px;font-weight:700;margin-bottom:2px">ClearFlow AI</div>
          <div style="color:#6b7280;font-size:12px">Generated on ${date}</div>
        </div>
        <div style="font-size:13px">
          <p>${bodyHtml}</p>
        </div>
        <div style="margin-top:32px;padding-top:10px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af">
          Generated by ClearFlow AI — AI-powered accounting
        </div>
      </div>
      <style>
        h1{font-size:18px;color:#111827;margin:20px 0 8px}
        h2{font-size:15px;color:#1f2937;margin:16px 0 6px}
        h3{font-size:13px;color:#374151;margin:12px 0 4px}
        ul{padding-left:18px;margin:6px 0}
        li{margin:3px 0}
        table{width:100%;border-collapse:collapse;margin:12px 0;font-size:12px}
        th{background:#eff6ff;color:#1e40af;padding:8px 12px;text-align:left;border:1px solid #bfdbfe}
        td{padding:7px 12px;border:1px solid #e5e7eb}
        tr:nth-child(even) td{background:#f9fafb}
        blockquote{border-left:3px solid #93c5fd;margin:10px 0;padding:6px 14px;background:#eff6ff;color:#1e40af}
        hr{border:none;border-top:1px solid #e5e7eb;margin:16px 0}
      </style>
    `;

    document.body.appendChild(container);
    html2pdf()
      .set({
        margin: [12, 14],
        filename: `clearflow-ai-report-${Date.now()}.pdf`,
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
      })
      .from(container)
      .save()
      .then(() => document.body.removeChild(container));
  };

  return (
    <div className="group flex justify-start">
      <div className="max-w-[75%]">
        <div className="bg-gray-100 text-gray-800 rounded-2xl rounded-bl-sm px-4 py-3 text-sm leading-relaxed">
          <ReactMarkdown
            remarkPlugins={[remarkGfm]}
            components={{
              h1: ({ children }) => <h1 className="text-base font-bold mt-2 mb-1">{children}</h1>,
              h2: ({ children }) => <h2 className="text-sm font-bold mt-2 mb-1">{children}</h2>,
              h3: ({ children }) => <h3 className="text-sm font-semibold mt-1 mb-0.5">{children}</h3>,
              p: ({ children }) => <p className="mb-1 last:mb-0">{children}</p>,
              ul: ({ children }) => <ul className="list-disc list-inside mb-1 space-y-0.5">{children}</ul>,
              ol: ({ children }) => <ol className="list-decimal list-inside mb-1 space-y-0.5">{children}</ol>,
              li: ({ children }) => <li className="ml-2">{children}</li>,
              strong: ({ children }) => <strong className="font-semibold">{children}</strong>,
              table: ({ children }) => (
                <div className="overflow-x-auto my-2">
                  <table className="min-w-full text-xs border border-gray-300 rounded">{children}</table>
                </div>
              ),
              thead: ({ children }) => <thead className="bg-gray-200">{children}</thead>,
              th: ({ children }) => <th className="px-3 py-1.5 text-left font-semibold border-b border-gray-300">{children}</th>,
              td: ({ children }) => <td className="px-3 py-1.5 border-b border-gray-200">{children}</td>,
              blockquote: ({ children }) => <blockquote className="border-l-2 border-gray-400 pl-3 italic text-gray-600 my-1">{children}</blockquote>,
              code: ({ children }) => <code className="bg-gray-200 rounded px-1 font-mono text-xs">{children}</code>,
              hr: () => <hr className="my-2 border-gray-300" />,
            }}
          >
            {content}
          </ReactMarkdown>
        </div>

        {/* Action buttons — visible on hover */}
        <div className="flex gap-2 mt-1 opacity-0 group-hover:opacity-100 transition-opacity">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1 text-xs text-gray-500 hover:text-gray-700 px-2 py-1 rounded hover:bg-gray-100 transition-colors"
          >
            {copied ? (
              <>
                <svg className="w-3.5 h-3.5 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                <span className="text-green-500">Copied!</span>
              </>
            ) : (
              <>
                <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                    d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                Copy
              </>
            )}
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1 text-xs text-gray-500 hover:text-gray-700 px-2 py-1 rounded hover:bg-gray-100 transition-colors"
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download
          </button>
        </div>
      </div>
    </div>
  );
}

const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;

export default function Chat() {
  const [messages, setMessages] = useState([INITIAL_MESSAGE]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [listening, setListening] = useState(false);
  const messagesEndRef = useRef(null);
  const recognitionRef = useRef(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading]);

  const newConversation = async () => {
    await api.delete("/chat/history").catch(() => {});
    setMessages([INITIAL_MESSAGE]);
    setError("");
  };

  const sendMessage = async () => {
    const text = input.trim();
    if (!text || loading) return;

    setInput("");
    setError("");
    setMessages((prev) => [...prev, { role: "user", content: text }]);
    setLoading(true);

    try {
      const res = await api.post("/chat", { message: text });
      setMessages((prev) => [...prev, { role: "assistant", content: res.data.reply }]);
    } catch (err) {
      setError(err.response?.data?.detail || "Failed to get a response. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const sendSuggestion = (question) => {
    if (loading) return;
    setInput("");
    setError("");
    setMessages((prev) => [...prev, { role: "user", content: question }]);
    setLoading(true);
    api.post("/chat", { message: question })
      .then((res) => setMessages((prev) => [...prev, { role: "assistant", content: res.data.reply }]))
      .catch((err) => setError(err.response?.data?.detail || "Failed to get a response. Please try again."))
      .finally(() => setLoading(false));
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const toggleVoice = () => {
    if (!SpeechRecognition) return;

    if (listening) {
      recognitionRef.current?.stop();
      setListening(false);
      return;
    }

    const recognition = new SpeechRecognition();
    recognition.lang = "en-US";
    recognition.interimResults = false;
    recognition.onresult = (e) => {
      const transcript = e.results[0][0].transcript;
      setInput(transcript);
      setListening(false);
    };
    recognition.onerror = () => setListening(false);
    recognition.onend = () => setListening(false);
    recognitionRef.current = recognition;
    recognition.start();
    setListening(true);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Ask Your Finances</h1>
          <p className="text-gray-500 text-sm mt-1">
            Chat with AI about your transactions, invoices, and cash flow.
          </p>
        </div>
        <button
          onClick={newConversation}
          disabled={loading}
          className="bg-white border border-gray-300 hover:bg-gray-50 disabled:opacity-50 text-gray-700 text-sm font-semibold px-4 py-2 rounded-lg transition-colors"
        >
          New Conversation
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-100 flex flex-col" style={{ height: "clamp(400px, 70vh, 700px)" }}>
        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-6 space-y-4">
          {messages.map((msg, i) =>
            msg.role === "user" ? (
              <div key={i} className="flex justify-end">
                <div className="max-w-[75%] rounded-2xl px-4 py-3 text-sm leading-relaxed bg-blue-600 text-white rounded-br-sm whitespace-pre-wrap">
                  {msg.content}
                </div>
              </div>
            ) : (
              <AssistantMessage key={i} content={msg.content} />
            )
          )}

          {loading && (
            <div className="flex justify-start">
              <div className="bg-gray-100 text-gray-500 rounded-2xl rounded-bl-sm px-4 py-3 text-sm">
                Thinking...
              </div>
            </div>
          )}

          {error && (
            <div className="flex justify-start">
              <div className="bg-red-50 text-red-600 border border-red-200 rounded-2xl px-4 py-3 text-sm">
                {error}
              </div>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Suggested questions — only shown on fresh conversation */}
        {messages.length === 1 && !loading && (
          <div className="px-6 pb-3 flex flex-wrap gap-2">
            {SUGGESTED_QUESTIONS.map((s) => (
              <button
                key={s.label}
                onClick={() => sendSuggestion(s.question)}
                className="text-xs px-3 py-1.5 rounded-full border border-blue-200 bg-blue-50 text-blue-700 hover:bg-blue-100 transition-colors"
              >
                {s.label}
              </button>
            ))}
          </div>
        )}

        {/* Input */}
        <div className="border-t border-gray-100 p-4 flex gap-3 items-end">
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            disabled={loading}
            rows={2}
            placeholder="Ask about your finances... (Enter to send, Shift+Enter for new line)"
            className="flex-1 border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none disabled:bg-gray-50 disabled:text-gray-400"
          />
          {SpeechRecognition && (
            <button
              onClick={toggleVoice}
              disabled={loading}
              className={`self-end p-2 rounded-lg transition-colors ${listening ? "bg-red-100 text-red-600 animate-pulse" : "text-gray-400 hover:text-gray-600 hover:bg-gray-100"}`}
              title={listening ? "Stop recording" : "Voice input"}
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
              </svg>
            </button>
          )}
          <button
            onClick={sendMessage}
            disabled={loading || !input.trim()}
            className="bg-blue-600 hover:bg-blue-700 disabled:bg-blue-300 text-white px-4 py-2 rounded-lg text-sm font-semibold transition-colors self-end"
          >
            {loading ? "..." : "Send"}
          </button>
        </div>
      </div>
    </div>
  );
}
